---
ahoyapi: v2

commands:
  up:
    usage: Build project.
    cmd: |
      docker compose up -d "$@" &&
      docker compose exec -T test dockerize -wait tcp://mariadb:3306 -timeout 2m &&
      ahoy info;

  down:
    usage: Delete project (CAUTION).
    cmd: |
      if [ "$1" == "y" ]; then
        docker compose down --volumes
      else
        ahoy confirm "Running this command will destroy your current site, database and build? Are you sure you didn't mean ahoy stop?" &&
        # Run this if confirm returns true
        docker compose down --volumes ||
        # Run this if confirm returns false
        echo "OK, probably a wise choice..."
      fi

  build:
    usage: Build project.
    cmd: |
      docker compose up -d --build "$@" &&
      docker compose exec -T test dockerize -wait tcp://mariadb:3306 -timeout 2m &&
      ahoy govcms-deploy && ahoy info;

  cli:
    usage: Start a shell inside cli container.
    cmd: docker compose exec cli bash

  run:
    usage: Run command inside cli container.
    cmd: docker compose exec -T cli bash -c "$*"

  govcms-deploy:
    usage: Runs deployment commands (e.g. config import, updb, cr, set up file_stage_proxy).
    cmd: |
      docker compose exec -T cli mkdir -p /app/web/sites/default/files/private/tmp && \
      docker compose exec -T cli /app/vendor/bin/govcms-db-update && \
      docker compose exec -T cli /app/vendor/bin/govcms-config-import && \
      docker compose exec -T cli /app/vendor/bin/govcms-cache-rebuild && \
      docker compose exec -T cli /app/vendor/bin/govcms-enable_modules

  drush:
    usage: Run drush commands in cli container.
    cmd: docker compose exec -T cli drush "$@"

  logs:
    usage: Show Docker logs.
    cmd: docker compose logs "$@"

  ps:
    usage: List running Docker containers.
    cmd: docker compose ps

  restart:
    usage: Restart Docker containers.
    cmd: docker compose restart

  stop:
    usage: Stop Docker containers.
    cmd: docker compose stop "$@"

  install:
    usage: Install the profile.
    cmd: docker compose exec -T cli drush si -y govcms "$@" && ahoy govcms-deploy

  login:
    usage: Login to a website.
    cmd: |
      docker compose exec -T cli drush -y cset tfa.settings reset_pass_skip_enabled true && \
      docker compose exec -T cli drush uinf --uid 1 --field name | xargs docker compose exec -T cli drush uublk && \
      docker compose exec -T cli drush uli

  unloop:
    usage: Fix local redirect loop
    cmd: |
      docker compose exec -T cli drush ev '$u=\Drupal\user\Entity\User::load(1); $u->set("field_password_expiration", "0"); $u->save()' && \
      docker compose exec -T cli drush ev '$u=\Drupal\user\Entity\User::load(1); $u->set("field_last_password_reset", date("Y-m-d\TH:i:s")); $u->save()'

  mysql-import:
    usage: Pipe in a sql file.  `ahoy mysql-import local.sql`
    cmd: |
      if [ -e "$@" ] ; then
        docker compose exec cli bash -c 'drush sql-drop' &&
        docker compose exec -T cli bash -c 'drush sql-cli' < "$@"
      else echo "Provided sql file" "$@" "does not exist"
      fi

  mysql-dump:
    usage: Dump data out into a file. `ahoy mysql-dump local.sql`
    cmd: docker compose exec -T cli bash -c 'drush sql-dump --ordered-dump' > "$@"

  lint:
    usage: Lint code
    cmd: |
      docker compose exec -T test ./vendor/bin/govcms-lint web/modules/custom
      docker compose exec -T test ./vendor/bin/govcms-lint web/themes/custom

  test-behat:
    usage: Run Behat tests.
    cmd: docker compose exec -T test ./vendor/bin/govcms-behat "$@"

  test-phpunit:
    usage: Run phpunit tests
    cmd: docker compose exec -T test ./vendor/bin/govcms-phpunit --testsuite govcms

  pull:
    usage: Pull latest docker images.
    cmd: docker image ls --format \"{{.Repository}}:{{.Tag}}\" | grep govcms/ | grep -v none | xargs -n1 docker pull | cat

  refresh-db:
    usage: Refresh the database container with latest nightly dump.
    cmd: |
      ahoy confirm "Running this command will replace your current database. Are you sure?" &&
      # Run this if confirm returns true
      ( cat .env | grep ^MARIADB_DATA_IMAGE | cut -c20- | xargs -n1 docker pull; docker compose rm -f -s -v mariadb && ahoy up ) ||
      # Run this if confirm returns false
      echo "OK, probably a wise choice..."

  ship-shape:
    usage: Run site validation scripts locally
    cmd: |
      docker compose exec -T cli shipshape -f /app/vendor/govcms/scaffold-tooling/shipshape.yml --exclude-db --error-code "$@"

  debug:
    usage: Enable debug configuration.
    cmd: |
      { ahoy run "php -v|grep -q Xdebug" && echo "Debug is already enabled"; } \
      || { export XDEBUG_ENABLE="true" && ahoy up cli test php nginx && ahoy run "php -v|grep -q Xdebug" && echo "Enabled debug configuration. Use 'ahoy up' to disable."; }

  info:
    usage: Print information about this project.
    cmd: |
      echo "Project                  : " $(ahoy run "echo \$LAGOON_PROJECT")
      echo "Site local URL           : " $(ahoy run "echo \$LAGOON_ROUTE")
      echo "DB port on host          : " $(docker port $(docker compose ps -q mariadb) 3306 | cut -d : -f 2)
      if [ "$1" ]; then
        echo "One-time login           : " $(ahoy login -- --no-browser)
      fi

  confirm:
    cmd: read -r -p "${@} [y/N] " response; [ ${response} = "y" ]
    hide: true

  my:
    usage: Custom commands for this project. See `ahoy my help`.
    imports:
      - 'custom/ahoy.yml'

  init:
    usage: Initialise codebase with project name, type (saas|paas|saasplus) and version (8|9)
    cmd: scripts/scaffold-init.sh -n $1 -t $2 -v $3

  #####################
  ## Lando commands ###
  #####################
  lando:
    service: cli
    cmd: echo Use \`ahoy lando-[command]\` to run specific ahoy lando commands instead.

  lando-up:
    usage: Build project. [Lando]
    cmd: |
      lando start "$@" &&
      ahoy lando-info;

  lando-down:
    usage: Delete project (CAUTION). [Lando]
    # `lando destroy` already has a prompt.
    cmd: lando destroy

  lando-build:
    usage: Build project. [Lando]
    cmd: |
      lando rebuild "$@"
      ahoy lando-govcms-deploy && ahoy lando-info;

  lando-cli:
    usage: Start a shell inside cli container. [Lando]
    cmd: lando ssh -s cli

  lando-run:
    usage: Run command inside cli container. [Lando]
    cmd: docker exec -it $(ahoy lando-app-name)_cli_1 bash -c "$*"

  lando-govcms-deploy:
    usage: Runs deployment commands (e.g. config import, updb, cr, set up file_stage_proxy). [lando]
    cmd: |
      lando ssh -s cli -c "mkdir -p /app/web/sites/default/files/private/tmp && \
      /app/vendor/bin/govcms-db-update && \
      /app/vendor/bin/govcms-config-import && \
      /app/vendor/bin/govcms-cache-rebuild && \
      /app/vendor/bin/govcms-enable_modules"

  lando-drush:
    usage: Run drush commands in cli container. [Lando]
    cmd: lando drush "$@"

  lando-logs:
    usage: Show Docker logs. [Lando]
    cmd: lando logs "$@"

  lando-ps:
    usage: List running Docker containers. [Lando]
    # Find Lando app name and pass to docker docker container ls
    cmd: ahoy lando-app-name | { read result; head -1; docker container ls -a | grep $result; }

  lando-restart:
    usage: Restart Docker containers. [Lando]
    cmd: lando restart

  lando-stop:
    usage: Stop Docker containers. [Lando]
    cmd: lando stop "$@"

  lando-install:
    usage: Install the profile. [Lando]
    cmd: |
      ahoy confirm "Running this command will destroy your current site, are you sure?" && \
      (lando ssh -u 0 -s cli -c "drush si -y govcms \"$@\"" && ahoy lando-govcms-deploy) || \
      echo "Cancelled."

  lando-login:
    usage: Login to a website. [Lando]
    cmd: |
      lando ssh -s cli -c "drush -y cset tfa.settings reset_pass_skip_enabled true" && \
      lando ssh -s cli -c "drush uinf --uid 1 --field name" | xargs -I % lando ssh -s cli -c "drush uublk %" && \
      lando ssh -s cli -c "drush uli"

  lando-unloop:
    usage: Fix local redirect loop [Lando]
    # Make the PHP code, escape it and run in docker not lando due to issue
    # lando/lando#212
    cmd: |
      DRUSH_TEMP_COMMAND=$(cat <<'END'
      $u=\Drupal\user\Entity\User::load(1); $u->set("field_password_expiration", "0"); $u->save();
      $u=\Drupal\user\Entity\User::load(1); $u->set("field_last_password_reset", date("Y-m-d\TH:i:s")); $u->save();
      END
      ); DRUSH_TEMP_COMMAND="$(printf "\"%q\"" $DRUSH_TEMP_COMMAND)"
      docker exec -it $(ahoy lando-app-name)_cli_1 bash -c "drush ev \"$DRUSH_TEMP_COMMAND\""

  lando-mysql-import:
    usage: Pipe in a sql file.  `ahoy lando-mysql-import local.sql` [Lando]
    cmd: |
      if [ -e "$@" ] ; then
        lando ssh -s cli -c 'drush sql-drop' &&
        lando ssh -s cli -c 'drush sql-cli' < "$@"
      else echo "Provided sql file" "$@" "does not exist"
      fi

  lando-mysql-dump:
    usage: Dump data out into a file. `ahoy lando-mysql-dump local.sql` [Lando]
    cmd: lando ssh -s cli -c 'drush sql-dump --ordered-dump' > "$@"

  lando-lint:
    usage: Lint code [Lando]
    cmd: |
      lando ssh -s test -c ./vendor/bin/govcms-lint web/modules/custom
      lando ssh -s test -c ./vendor/bin/govcms-lint web/themes/custom

  lando-test-behat:
    usage: Run Behat tests. [Lando]
    cmd: lando ssh -s test -c ./vendor/bin/govcms-behat "$@"

  lando-test-phpunit:
    usage: Run phpunit tests [Lando]
    cmd: lando ssh -s test -c ./vendor/bin/govcms-phpunit --testsuite govcms

  lando-refresh-db:
    usage: Refresh the database container with latest nightly dump. [Lando]
    cmd: |
      ahoy confirm "Running this command will replace your current database. Are you sure?" &&
      ( cat .env | grep ^MARIADB_DATA_IMAGE | cut -c20- \
      | xargs -n1 docker pull; docker rm -f -v $(ahoy lando-app-name)_mariadb_1 \
      && lando start ) ||
      echo OK, probably a wise choice...

  lando-ship-shape:
    usage: Run site validation scripts locally [Lando]
    cmd: |
      docker exec -it $(ahoy lando-app-name)_cli_1 bash -c "shipshape -f /app/vendor/govcms/scaffold-tooling/shipshape.yml --exclude-db --error-code \"$@\""

  lando-debug:
    usage: Enable debug configuration. [Lando]
    cmd: |
      { ahoy lando-run "php -v|grep -q Xdebug" && echo "Debug is already enabled. Use \`export XDEBUG_ENABLE="" && lando rebuild\` to disable."; } \
      || { export XDEBUG_ENABLE="true" && lando rebuild && \
      ahoy lando-run "php -v|grep -q Xdebug" && echo "Enabled debug configuration. Use \`export XDEBUG_ENABLE="" && lando rebuild\` to disable." || \
      echo "Enabling debug configuration failed."; }

  lando-info:
    usage: Print information about this project.  [Lando]
    cmd: |
      echo "Project                  : "$(ahoy lando-run "echo \$LAGOON_PROJECT" 2>/dev/null)
      echo "Site local URL           : "$(ahoy lando-run "echo \$LAGOON_ROUTE" 2>/dev/null)
      echo "DB port on host          : "$(docker port $(ahoy lando-app-name 2>/dev/null)_mariadb_1 3306 | cut -d : -f 2)
      if [ "$1" ]; then
        echo "One-time login           : " $(ahoy lando-login -- --no-browser)
      fi

  # Helpers.
  lando-app-name:
    cmd: lando info 2>/dev/null | grep hostnames | grep -o -P "[^\.]*.internal('|\")" | awk -F . '{print $1}' | head -n 1
    hide: true
