# This file is used for integration with GovCMS on Lagoon. Don't remove it!
#
# It's used to identify the type and version of a PaaS or SaaS project.
# Automated GovCMS tasks read this file to determine which processes to run -
# e.g. site audits, automated backups.
version: 8
type: saas
scaffold: 2.0.0
