#!/usr/bin/env bash
##
# GovCMS 8 PaaS Drupal deployment script.
#

# Ensure tmp folder always exists.
mkdir -p /app/web/sites/default/files/private/tmp/

# Non production environments.
if [[ "$LAGOON_ENVIRONMENT_TYPE" != "production" ]]; then
    # Import production database on initial deployment (when database is empty).
    if tables=$(drush sqlq 'show tables;') && [ -z "$tables" ]; then

        # SQL sync only in Lagoon development environments.
        if [[ ! -z "$LAGOON_ENVIRONMENT_TYPE" && "$LAGOON_ENVIRONMENT_TYPE" != "local" ]]; then
          drush sql-sync @govcms-prod @self -y

          # Enable stage file proxy post db-import.
          drush en stage_file_proxy -y
        fi

    else
      # Enable stage file proxy.
      drush en stage_file_proxy -y
    fi

# Production environments.
else

  if tables=$(drush sqlq 'show tables;') && [ -n "$tables" ]; then

    mkdir -p /app/web/sites/default/files/private/backups/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/backups/pre-deploy-dump.sql
    drush en -y govcms_lagoon && drush pmu -y govcms_lagoon;
  else
    echo "Drupal not installed."
  fi

fi

# All valid environments.
if tables=$(drush sqlq 'show tables;') && [ -n "$tables" ]; then
  drush updb -y
  drush cr
fi

