#!/usr/bin/env bash
# Code linting for SaaS project.

TESTS_DIR=${TESTS_DIR:-/tests}
PROFILE_DIR=${PROFILE_DIR:-/app/web}
APP_DIR=${APP_DIR:-/app}

# Lint code.
${TESTS_DIR}/vendor/bin/parallel-lint --exclude /app/vendor -e php,inc,module,theme,install,profile,test ${PROFILE_DIR}/themes/custom

# Check code standards.
${TESTS_DIR}/vendor/bin/phpcs --standard=${APP_DIR}/tests/phpcs.xml ${PROFILE_DIR}/themes/custom

# Check code mess.
${TESTS_DIR}/vendor/bin/phpmd ${PROFILE_DIR}/themes/custom text codesize,unusedcode,cleancode
