##
# @see  https://govcms.gov.au/wiki-advanced#docker
#

ARG CLI_IMAGE
ARG GOVCMS_IMAGE_VERSION={{ GOVCMS_VERSION }}.x-latest

FROM ${CLI_IMAGE} as cli
FROM govcms/test:${GOVCMS_IMAGE_VERSION}

ENV WEBROOT=web

COPY --from=cli /app /app
COPY tests /app/tests/
