##
# @see  https://govcms.gov.au/wiki-advanced#docker
#

ARG CLI_IMAGE
ARG GOVCMS_IMAGE_VERSION={{ GOVCMS_VERSION }}.x-latest

FROM ${CLI_IMAGE} as cli
FROM govcms/test:${GOVCMS_IMAGE_VERSION}

ENV WEBROOT=web

COPY --from=cli /app /app
COPY tests /app/tests/

# Copy deploy and test scripts.
RUN cp /app/vendor/govcms/scaffold-tooling/scripts/govcms* /usr/local/bin/
RUN chmod +x /usr/local/bin/*

# @see also drush setup in Dockerfile.cli
COPY --from=cli /usr/local/bin/drush /usr/local/bin/
RUN chmod +x /usr/local/bin/drush && rm -Rf /home/.composer/vendor/bin
# Drutiny expects "drush-launcher" which is not the idea of drush-launcher. Hack around it.
RUN cp /usr/local/bin/drush /usr/local/bin/drush-launcher && chmod +x /usr/local/bin/drush-launcher
