##
# `nginx-drupal` image
#
# This image is derived from php-fpm, which lacks tools to build Drupal.
# The files are therefore copied from the `cli` container (Dockerfile.cli) which is built first.
#

ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

FROM govcms8lagoon/nginx-drupal

RUN rm -rf /app
# nginx only needs the root and any static files that are there, the rest is handled by the php container.
COPY --from=cli /app/web /app/web

# Define where the Drupal Root is located
ENV WEBROOT=web
