##
# @see  https://govcms.gov.au/wiki-advanced#docker
#
FROM uselagoon/solr-8

# Based off search_api_solr/jump-start/solr8/config-set as a sane default.
COPY .docker/config/solr/ /opt/solr/server/solr/configsets/drupal/conf

USER solr

# Note: The solr-recreate command will remove and replace.
# If your configuration has changed you may need to reindex your solr index.
CMD solr-recreate drupal /opt/solr/server/solr/configsets/drupal && solr-foreground