##
# @see  https://govcms.gov.au/wiki-advanced#docker
#
FROM uselagoon/solr-8

# Based off search_api_solr/jump-start/solr8/config-set as a sane default.
COPY .docker/config/solr/ /opt/solr/server/solr/configsets/drupal/conf

USER solr

RUN precreate-core drupal /opt/solr/server/solr/configsets/drupal
CMD ["solr-foreground"]