##
# @see  https://govcms.gov.au/wiki-advanced#docker
#

ARG CLI_IMAGE
ARG GOVCMS_IMAGE_VERSION=latest

FROM govcms8lagoon/govcms8:latest

ENV WEBROOT=web

COPY custom /app/custom

RUN rm composer.lock && composer install -d /app && composer clearcache

COPY themes/ /app/web/themes/custom
COPY config /app/config

# Default application favicon this will be used for files and server
# error pages all other favicon requests will be surfaced via Drupal.
COPY favicon.ico /app/web
